### ISSUE TITLE
Exception when testing analyze

### ISSUE THREAD

**Issue by lequi** [iotlinkadmin/map4d-tokenizer-elasticsearch#1]
I have build this plugin for elasticsearch 7.2.0. But when I call testing analyze, it's throw exception below:

OpenJDK 64-Bit Server VM warning: You have loaded library /usr/share/elasticsearch/plugins/coccoc-tokenizer-plugin/coccoc-tokenizer/libcoccoc_tokenizer_jni.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
{"type": "server", "timestamp": "2019-07-08T09:56:06,524+0000", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "5a9a472dd89e", "cluster.uuid": "rj7Ua7gfSqi1QBAB0t5GKg", "node.id": "1X5kn6jhRwyPXfZ_VW9Pfw",  "message": "fatal error in thread [elasticsearch[5a9a472dd89e][analyze][T#1]], exiting" ,
"stacktrace": ["java.lang.UnsatisfiedLinkError: /usr/share/elasticsearch/plugins/coccoc-tokenizer-plugin/coccoc-tokenizer/libcoccoc_tokenizer_jni.so: /usr/share/elasticsearch/plugins/coccoc-tokenizer-plugin/coccoc-tokenizer/libcoccoc_tokenizer_jni.so: invalid ELF header (Possible cause: endianness mismatch)",
"at java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]",
"at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[?:?]",
"at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[?:?]",
"at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[?:?]",
"at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[?:?]",
"at java.lang.Runtime.load0(Runtime.java:765) ~[?:?]",
"at java.lang.System.load(System.java:1866) ~[?:?]",
"at com.coccoc.Tokenizer.<clinit>(Tokenizer.java:23) ~[?:?]",
"at java.security.AccessController.doPrivileged(AccessController.java:310) ~[?:?]",
"at org.apache.lucene.analysis.CocCocTokenizer.<init>(CocCocTokenizer.java:46) ~[?:?]",
"at org.elasticsearch.index.analysis.CocCocTokenizerFactory.create(CocCocTokenizerFactory.java:24) ~[?:?]",
"at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:100) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]",
"at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:263) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:246) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:165) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:82) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:113) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]",
"at java.lang.Thread.run(Thread.java:835) [?:?]"] }

**Comment by dinhhuy258** [comment]
The binary release file just works on MacOS. 
If you are using Linux OS. Please download the source code and build it your own.

**Comment by lequi** [comment]
> The binary release file just works on MacOS.
> If you are using Linux OS. Please download the source code and build it your own.

I have download the source code & build it on MacOS, then copy release file to Docker and install it on container.
I will try to build on docker container.

Thank you.
